<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::all()->keyBy('slug');

        $products = [
            [
                'category_slug' => 'carry-and-bags',
                'name' => 'Heavy Canvas Utility Tote Bag',
                'slug' => 'heavy-canvas-utility-tote-bag',
                'sku' => 'MN-001',
                'price' => 385000,
                'stock' => 24,
                'summary' => 'Tas jinjing kanvas katun 16oz dengan kompartemen laptop dan tali strap anyam tebal.',
                'description' => "Tas jinjing dirancang untuk kebutuhan mobilitas harian dengan material kanvas katun berkekuatan tinggi 16oz. Dilengkapi kompartemen busa pelindung laptop hingga ukuran 15 inci, saku botol internal, dan saku ritsleting YKK tersembunyi untuk barang berharga.\n\nSetiap titik tegangan diperkuat dengan jahitan bar-tack industri ganda guna menjamin ketahanan pakai jangka panjang.",
                'specifications' => [
                    'Material' => '16oz Cotton Duck Canvas Heavyweight',
                    'Dimensi' => '40cm x 36cm x 14cm',
                    'Kapasitas' => '20 Liter',
                    'Kompartemen' => 'Laptop sleeve 15 inch + 2 Organizer pocket',
                    'Hardware' => 'Ritsleting Logam YKK Hitam Matte',
                    'Warna' => 'Raw Black / Off-White Natural',
                ],
                'image_path' => 'images/products/mono-tote.svg',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_slug' => 'carry-and-bags',
                'name' => 'Urban Rolltop Tactical Backpack',
                'slug' => 'urban-rolltop-tactical-backpack',
                'sku' => 'MN-002',
                'price' => 645000,
                'stock' => 15,
                'summary' => 'Ransel tahan air Cordura 500D dengan sistem penutup rolltop magnetik Fidlock.',
                'description' => "Backpack modern yang memadukan siluet monokrom arsitektural dengan utilitas cuaca ekstrem. Material dasar tahan air DWR-coated Cordura 500D melindungi seluruh perlengkapan elektronik dari hujan lebat.\n\nDilengkapi ritsleting akses samping kilat ke kompartemen utama dan bantalan punggung berongga sirkulasi udara.",
                'specifications' => [
                    'Material' => 'Cordura 500D Ballistic Nylon Waterproof',
                    'Dimensi' => '48cm - 62cm (Rolltop) x 30cm x 16cm',
                    'Kapasitas' => '24 - 30 Liter',
                    'Aksesori' => 'Buckle magnetik aluminium quick-release',
                    'Bobot' => '850 gram',
                ],
                'image_path' => 'images/products/mono-backpack.svg',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_slug' => 'apparel-and-wear',
                'name' => 'Heavyweight 240gsm Boxy Fit Tee',
                'slug' => 'heavyweight-240gsm-boxy-fit-tee',
                'sku' => 'MN-003',
                'price' => 195000,
                'stock' => 50,
                'summary' => 'Kaus katun combed 16s 240gsm dengan siluet potongan boxy dan kerah kaku rib 3cm.',
                'description' => "Kaus monokrom esensial dengan konstruksi kain katun combed 100% berbobot 240 GSM. Potongan boxy modern yang jatuh tegap tanpa melar setelah proses pencucian berulang. Kerah berkerapatan tinggi menjamin bentuk tetap simetris.",
                'specifications' => [
                    'Material' => '100% Combed Cotton Heavyweight 240 GSM',
                    'Fit' => 'Relaxed Boxy Drop-Shoulder',
                    'Kerah' => 'Tight Rib 3.0cm Cotton Elastane',
                    'Jahitan' => 'Double needle stitch collar & hem',
                    'Perawatan' => 'Cuci dingin, setrika temperatur sedang',
                ],
                'image_path' => 'images/products/mono-tee.svg',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_slug' => 'apparel-and-wear',
                'name' => 'Archive French Terry Pullover Hoodie',
                'slug' => 'archive-french-terry-pullover-hoodie',
                'sku' => 'MN-004',
                'price' => 450000,
                'stock' => 18,
                'summary' => 'Hoodie bertudung ganda dari katun French Terry 380gsm tanpa tali untuk estetika bersih.',
                'description' => "Hoodie pullover tanpa tali serut menghadirkan visual bersih khas minimalis arsitektur. Kain katun French Terry 380 GSM memberikan kehangatan teratur dan sirkulasi udara sejuk saat dipakai harian.",
                'specifications' => [
                    'Material' => '100% Cotton Heavy French Terry 380 GSM',
                    'Kapuchon' => 'Double-layered structured hood (cordless)',
                    'Saku' => 'Kangaroo pouch bersembunyi',
                    'Manset' => 'Thick ribbed cuff & waistband',
                ],
                'image_path' => 'images/products/mono-hoodie.svg',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_slug' => 'apparel-and-wear',
                'name' => 'Structured 6-Panel Minimalist Cap',
                'slug' => 'structured-6-panel-minimalist-cap',
                'sku' => 'MN-005',
                'price' => 165000,
                'stock' => 32,
                'summary' => 'Topi 6-panel berbahan twill katun kaku dengan strap gesper kuningan hitam.',
                'description' => "Topi klasik 6-panel berprofil medium tanpa grafis mencolok. Mahkota terstruktur dengan pelapis kanvas internal mempertahankan proporsi bentuk optimal di kepala.",
                'specifications' => [
                    'Material' => 'Heavy Cotton Chino Twill',
                    'Profil' => 'Medium Crown 6-Panel Structured',
                    'Closure' => 'Twill strap dengan gesper kuningan hitam doff',
                    'Ukuran' => 'All size (lingkar kepala 55-61 cm)',
                ],
                'image_path' => 'images/products/mono-cap.svg',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_slug' => 'stationery-and-desk',
                'name' => 'Hardcover 5mm Grid Archive Journal',
                'slug' => 'hardcover-5mm-grid-archive-journal',
                'sku' => 'MN-006',
                'price' => 145000,
                'stock' => 40,
                'summary' => 'Buku catatan bersampul linen hitam dengan kertas 100gsm ramah pena bulu tinta.',
                'description' => "Journal sampul keras berserat kain linen hitam pekat. Menggunakan 192 halaman kertas acid-free 100 GSM bergaris grid 5mm abu-abu lembut yang tidak tembus saat ditulis pena tinta basah.",
                'specifications' => [
                    'Sampul' => 'Hardcover Cloth Bookbinding Linen Hitam',
                    'Kertas' => '100 GSM FSC-Certified Acid-free Paper',
                    'Halaman' => '192 halaman (Grid 5mm presisi)',
                    'Fitur' => 'Ribbon bookmark ganda & saku belakang ekspansi',
                    'Buka Datar' => 'Jilid benang 180 derajat flat-lay',
                ],
                'image_path' => 'images/products/mono-notebook.svg',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_slug' => 'stationery-and-desk',
                'name' => 'Machined Matte Aluminum Rollerball Pen',
                'slug' => 'machined-matte-aluminum-rollerball-pen',
                'sku' => 'MN-007',
                'price' => 285000,
                'stock' => 20,
                'summary' => 'Pena rollerball bermesin CNC presisi dari paduan aluminium anodized 6061-T6.',
                'description' => "Pena monolitik yang dibubut dari balok paduan aluminium antariksa. Keseimbangan titik tumpu berada tepat di ujung cengkeraman jari untuk pengalaman menulis panjang tanpa kelelahan otot.",
                'specifications' => [
                    'Material' => 'Aluminium Aerospace Anodized 6061-T6',
                    'Refill' => 'Kompatibel Schmidt P8126 / G2 Standard',
                    'Mata Pena' => '0.5mm Ceramic Rollerball',
                    'Bobot' => '32 gram',
                    'Finishing' => 'Black Satin Bead-blasted',
                ],
                'image_path' => 'images/products/mono-pen.svg',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_slug' => 'stationery-and-desk',
                'name' => 'Architectural Felt Desk Mat & Brass Tray',
                'slug' => 'architectural-felt-desk-mat-brass-tray',
                'sku' => 'MN-008',
                'price' => 260000,
                'stock' => 14,
                'summary' => 'Alas meja wol felt tebal 4mm dengan wadah aksesoris baja karbon terpadu.',
                'description' => "Bantalan meja kerja premium peredam suara gesekan keyboard dan alas mouse presisi. Terbuat dari serat wol alami padat yang tidak rontok dan tahan tumpahan air ringan.",
                'specifications' => [
                    'Material' => 'Natural Pressed Wool Felt 4.0mm',
                    'Dimensi' => '80cm x 35cm',
                    'Dasar' => 'Natural rubber antiselip bersertifikat',
                    'Aksesoris' => '1x Tray logam organizer beralur',
                ],
                'image_path' => 'images/products/mono-organizer.svg',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_slug' => 'living-and-objects',
                'name' => 'Vacuum Insulated Flask 600ml',
                'slug' => 'vacuum-insulated-flask-600ml',
                'sku' => 'MN-009',
                'price' => 310000,
                'stock' => 28,
                'summary' => 'Termos baja tahan karat 316 berdinding ganda dengan isolasi vakum 24 jam.',
                'description' => "Botol minum isolasi vakum berdinding ganda dari stainless steel medis 316. Mampu mempertahankan temperatur dingin es hingga 24 jam dan panas kopi hingga 12 jam tanpa rasa logam pada minuman.",
                'specifications' => [
                    'Material' => 'Medical Grade SUS 316 Inner Wall, SUS 304 Outer',
                    'Kapasitas' => '600 ml',
                    'Isolasi' => 'Double-wall Vacuum Thermal Barrier',
                    'Tutup' => 'Leakproof screw cap dengan handel silikon',
                    'Finishing' => 'Matte Powder Coating Anti Gores',
                ],
                'image_path' => 'images/products/mono-bottle.svg',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_slug' => 'living-and-objects',
                'name' => 'Matte Ceramic Pour-Over Coffee Mug',
                'slug' => 'matte-ceramic-pour-over-coffee-mug',
                'sku' => 'MN-010',
                'price' => 135000,
                'stock' => 35,
                'summary' => 'Cangkir keramik stoneware pembakaran suhu 1280°C dengan glasir matte arang.',
                'description' => "Cangkir kopi artisanal hasil pembakaran suhu tinggi berkapasitas 320ml. Memiliki ketebalan bibir cangkir ergonomis yang mengarahkan aliran cairan secara halus ke indera perasa.",
                'specifications' => [
                    'Material' => 'High-fired Stoneware Ceramic',
                    'Glasir' => 'Food-grade Charcoal Matte Glaze',
                    'Kapasitas' => '320 ml',
                    'Fitur' => 'Microwave & Dishwasher Safe',
                ],
                'image_path' => 'images/products/mono-mug.svg',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Ultra-Slim Full-Grain Leather Card Sleeve',
                'slug' => 'ultra-slim-full-grain-leather-card-sleeve',
                'sku' => 'MN-011',
                'price' => 220000,
                'stock' => 25,
                'summary' => 'Dompet kartu kulit nabati asli dengan 4 slot kartu dan saku tengah uang tunai.',
                'description' => "Dompet kartu ramping dengan ketebalan hanya 4mm dalam kondisi terisi. Dibuat menggunakan kulit nabati full-grain asal Tuscany yang akan menua membentuk patina gelap alami seiring pemakaian.",
                'specifications' => [
                    'Material' => '100% Vegetable Tanned Full-Grain Cowhide',
                    'Kapasitas' => '4 Slot kartu luar + 1 Kompartemen tengah',
                    'Dimensi' => '10cm x 7cm x 0.4cm',
                    'Jahitan' => 'Saddle stitch tangan dengan benang wax Jepang',
                ],
                'image_path' => 'images/products/mono-wallet.svg',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_slug' => 'accessories',
                'name' => 'Bauhaus Monochromatic Field Watch 38mm',
                'slug' => 'bauhaus-monochromatic-field-watch-38mm',
                'sku' => 'MN-012',
                'price' => 890000,
                'stock' => 8,
                'summary' => 'Jam tangan dial dial minimalis 38mm kaca safir dan mesin kuarsa presisi Miyota.',
                'description' => "Jam tangan estetika Bauhaus dengan casing stainless steel 316L berlapis PVD hitam matte. Dial putih bersih berindeks garis tipis tanpa angka memberikan keterbacaan waktu tanpa distraksi.",
                'specifications' => [
                    'Movement' => 'Japanese Quartz Miyota Caliber 1L45',
                    'Diameter Casing' => '38 mm (Ketebalan 7.8 mm)',
                    'Kaca' => 'Sapphire Crystal Anti-Reflective Coating',
                    'Tali' => 'Black Cordura Quick-Release 20mm',
                    'Ketahanan Air' => '5 ATM / 50 Meter',
                ],
                'image_path' => 'images/products/mono-watch.svg',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($products as $data) {
            $catSlug = $data['category_slug'];
            unset($data['category_slug']);
            $data['category_id'] = $categories[$catSlug]->id ?? null;

            Product::query()->updateOrCreate(['sku' => $data['sku']], $data);
        }
    }
}
